defaults:
        - _self_
        - runner: eval
        - dataset: badminton
        - model: wasb
        - dataloader: default
        - detector: tracknetv2
        - transform: default
        - tracker: online
hydra:
  run:
    # dir: /root/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}   # linux环境
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}   # windows环境
output_dir:
seed: 1234

